### ISSUE TITLE
Can't clone theme repository

### ISSUE THREAD

**Issue by saarcoder** [plenti-themes/bigspring#3]
Hi Jim,
when trying to clone the theme locally with `plenti theme add git@github.com:plenti-themes/bigspring` I am getting the following *Go error message:*
 
2021/11/22 09:40:46 errs.go:57: Can't clone theme repository: error creating SSH agent: "Error connecting to SSH_AUTH_SOCK: dial unix /run/user/1000/keyring/ssh: connect: permission denied"
error creating SSH agent: "Error connecting to SSH_AUTH_SOCK: dial unix /run/user/1000/keyring/ssh: connect: permission denied" (File: /home/runner/work/plenti/plenti/cmd/theme_add.go, Line: 75)
2021/11/22 09:40:46 errs.go:57: Can't get HEAD: reference not found
reference not found (File: /home/runner/work/plenti/plenti/cmd/theme_add.go, Line: 84)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa0aa45]

goroutine 1 [running]:
github.com/go-git/go-git/v5/plumbing.(*Reference).Hash(...)
	/home/runner/go/pkg/mod/github.com/go-git/go-git/v5@v5.2.0/plumbing/reference.go:183
github.com/plentico/plenti/cmd.getCommitHash(0xc0001ce120, 0x10, 0x7ffe42899e49)
	/home/runner/work/plenti/plenti/cmd/theme_add.go:87 +0x125
github.com/plentico/plenti/cmd.glob..func8(0x24e5e40, 0xc0001ad550, 0x1, 0x1)
	/home/runner/work/plenti/plenti/cmd/theme_add.go:54 +0x137
github.com/spf13/cobra.(*Command).execute(0x24e5e40, 0xc0001ad530, 0x1, 0x1, 0x24e5e40, 0xc0001ad530)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x24e5440, 0xc000000180, 0x200000003, 0xc000000180)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/plentico/plenti/cmd.Execute()
	/home/runner/work/plenti/plenti/cmd/root.go:60 +0x31
main.main()
	/home/runner/work/plenti/plenti/main.go:7 +0x25

Cloning with this command adds folders and files, but all subfolders are empty.

## Plenti version: 
v0.4.26

## OS
Operating System: elementary OS 5.1.7 Hera
Kernel: Linux 5.4.0-90-generic
Architecture: x86-64

**Comment by jimafisk** [comment]
Hi @saarcoder! Thanks for the detailed bug report. The `ssh: connect: permission denied` error message you're getting leads me to believe that maybe you haven't uploaded your SSH key to GitHub? 

Do you have any better luck if instead of using SSH like you were before:
```
plenti theme add git@github.com:plenti-themes/bigspring
```

You try using HTTPS (which doesn't require a key being uploaded to GitHub) like this:

```
plenti theme add https://github.com/plenti-themes/bigspring
```

If that doesn't fix the issue just let me know and I'll take a closer look! Thanks!

**Comment by saarcoder** [comment]
Perfect! Thank you Jim!
